apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oauth2-server
  template:
    metadata:
      labels:
        app: oauth2-server
    spec:
      containers:
        - name: app
          image: jyotirmayapati001/oauth2-server:cicd
          ports:
            - containerPort: 8083
          imagePullPolicy: IfNotPresent
---          
apiVersion: v1
kind: Service
metadata:
  name: oauth2-server
spec:
  selector:
    app: oauth2-server
  ports:
    - port: 80
      targetPort: 8083
  type: NodePort          
