client:
    id: NSjdziqWGTWHENlgsFfUKErUVbCGLa
    secret: LvaxCqfjSHyItBYtXhgVmelaWRnwhY
    
token:
    issuer:
        uri: http://13.236.136.227:8083
        
cors:
    allowed:
        uri: http://13.236.136.227:32649
        
        
server:
  port: 8083
